### ISSUE TITLE
Have you published this plugin?

### ISSUE THREAD

**Issue by ooker777** [dsarman/better-inline-fields#1]
Great plugin. However I'm unable to find it in [Plugins - Obsidian](https://obsidian.md/plugins)

**Comment by dsarman** [comment]
Thanks, I did not attempt to publish it yet. I will try to get to it in the next few weeks.

**Comment by ooker777** [comment]
Is it because you don't have time or you still need to improve it?

**Comment by dsarman** [comment]
It was both. But I just created PR to add it to the official plugin repository at https://github.com/obsidianmd/obsidian-releases/pull/1077, so lets see how it goes.

**Comment by dsarman** [comment]
Closing this issue as the plugin is now avilable in the official Bbsidian plugin repository
