### ISSUE TITLE
Allow multiple, separated folders for a field

### ISSUE THREAD

**Issue by ooker777** [dsarman/better-inline-fields#11]
I suppose you can have the `folder` entry accepts both string and array. E.g.:
```json
{
  "autocomplete": [
    {
      "field": "field A",
      "folder": "path/to/string"
    },
    {
      "field": "field B",
      "folder": ["path 1/to/string", "path 2/to/string"] 
    }
  ],
}
```
Or even in each folder, allow it to be the target of a specific source:
```json
{
  "field": "field B",
  "folder": [
    {
      "target": "path 1/to/target",
      "source": "path 1/to/source" 
    },
    {
      "target": "path 2/to/target",
      "source": "path 2/to/source" 
    }
  ] 
}
```
So if your current note is on `path 1/to/source`, then when you type `field B` the selection only displays notes from `path 1/to/target` and not display notes from `path 2/to/target`.

Would this be much headache to you?

**Comment by dsarman** [comment]
Unfortunately I will not have time to implement any new features in the near future.
But feel free to submit a PR if you want to.

**Comment by ooker777** [comment]
I wonder why you don't just leave the issue opened? What's your priority in letting issues opened?

**Comment by dsarman** [comment]
I view open issues as a sort of TODO list of things that I am planning to actively work on. If the situation changes, the issue can always be reopened.
