### ISSUE TITLE
Advanced suggestion filtering

### ISSUE THREAD

**Issue by ooker777** [dsarman/better-inline-fields#3]
I think there are two ways to make the suggestion more advanced:

- Search with regex
- Restrict the options in the dropdown in advance

The first one can use used for any field and in action. The second one can only be configured for each individual field and in advance in the setting.

If you have time to work on this, then it is so great. Otherwise can you tell me where I should start? I have written a basic plugin, but my coding skill is not strong

**Comment by dsarman** [comment]
The regex search should be pretty easy, I will try to look at it over the weekend.
What would you have in mind for "Restrict the options in the dropdown in advance"? Something like having a text input in settings for every completion folder where you could write regex matching ignored pages?

**Comment by ooker777** [comment]
Yes. For example your folder have note A, B and C. In the setting you have a "not A" requirement so the drop down only display B and C

**Comment by dsarman** [comment]
The regex search is out in version [0.1.4](https://github.com/dsarman/better-inline-fields/releases/tag/0.1.4), so you can try it out. I will get to the options restriction later.
