### ISSUE TITLE
How to make the plugin trigger on sentence-inside fields?

### ISSUE THREAD

**Issue by ooker777** [dsarman/better-inline-fields#4]
For example, is it possible to have it trigger for `rating` and `mood` inside this sentence?
```
I would rate this a [rating:: ...]! It was [mood:: ...].
```

**Comment by dsarman** [comment]
This was previously not possible. I added the functionality to version 0.2.0, so please update and try it out.

**Comment by ooker777** [comment]
Why was it previously impossible? Or did you just mean that it didn't have this feature then?

**Comment by dsarman** [comment]
Yes, I just meant that it did not have this feature until now.
