### ISSUE TITLE
Checking a task with the form of `- [ ] field:: false` should set it to true (and vice versa) and hide the tickbox on the right

### ISSUE THREAD

**Issue by blanelegant** [dsarman/better-inline-fields#6]
For example, given a todo:

```
- [ ] brush teeth in morning [teeth1:: false]
```

Checking the box, either by using a hotkey to cycle the state or by putting an `x` into the brackets, should also toggle the state of any inline field at the end of the line:

```
- [x] brush teeth in morning [teeth1:: true]
```

Unchecking the box would do the same in reverse. For inline fields on the same line as a todo like this, we should not display the secondary checkbox to the right like usual.

**Comment by dsarman** [comment]
I would ask why do you need this? I think you can achieve the same effect just with Dataview.
If you tag the todo like this:
`- [ ] brush teeth in morning #teeth1`
you can query the same information as in your example by filtering tasks by the tag and then checking if that task is completed.
