### ISSUE TITLE
Feature Request - Enhanced Inline Fields for Better Customization of Checklists

### ISSUE THREAD

**Issue by sfdrada** [dsarman/better-inline-fields#7]
Dear Obsidian Development Team,

I hope this message finds you well. First off, I want to thank you for your excellent work on Obsidian and the Inline Fields plugin. The plugin has provided valuable flexibility in crafting notes, and the overall Obsidian platform is undoubtedly one of the best note-taking tools available today. However, I would like to propose a couple of enhancements that, in my view, could make the Inline Fields plugin even more powerful and user-friendly.

1. **Customizable Checkbox Spacing**: Currently, the distance between the checkbox and the inline field is fixed. This sometimes results in a cramped visual appearance, especially when using checklists with longer inline fields. I propose adding a customization option that allows users to adjust the space between the checkbox and the text. This added control would enable us to create checklists that are not only functional but also visually pleasing and easy to read.

2. **Moving the Checklist to the Beginning of the Line**: In the current design, the checklist appears at the end of the line in inline fields. While this works well in many instances, there are situations where having the checklist at the beginning of the line would be more intuitive and efficient. I suggest adding a feature that allows users to choose the position of the checklist (beginning or end of the line) based on their preference.

These enhancements would provide an additional layer of flexibility and customization to the Inline Fields plugin, allowing users to tailor their Obsidian experience further to their specific needs and workflows.

Thank you for considering these suggestions. I believe that these enhancements would greatly benefit the Obsidian user community and promote even more widespread adoption of this fantastic tool.

Awesome Work,
Sage

![image](https://github.com/dsarman/better-inline-fields/assets/79337513/eb128a05-977e-454a-89dd-ddfe6596e087)

**Comment by dsarman** [comment]
Hi Sage,
please note that I (and this plugin) is in no way affiliated with the official Obsidian develoment team.

As for the feature request:
1. You can already customize the look of the checkboxes yourself using css snippets (Obsidian docs [here](https://help.obsidian.md/Extending+Obsidian/CSS+snippets)). Making them look good with different themes is hard, so they are optimized for the theme I am using.
As an example, to position the checkbox more to the top and right (according to your screenshot) you wold use a snippet like this:
```css
.bif-boolean-toggle {
    left: 2px;
    top: -2px;
}
```

2. Would a global toggle (either all checkboxes on the left, or on the right) work for you? That would be the easiest and fastest option to implement. The alternative is to mark the preffered side on the task itself (perhaps by using a specific tag), and render it based on that, but that would take more time to implement.

**Comment by sfdrada** [comment]
Thanks for the quick response dsarman,

1. Good to know this is a quick and easy fix, I'll definitely try this out

2. Personally a global toggle would work just fine, maybe a consideration would be to have an individual toggle for each data type to offer people more options on which they want to use where.

Thanks for the fast and valued development, 
Sage

**Comment by dsarman** [comment]
I am not sure what you mean by toggle for each data type. This plugin currently handles checkboxes only next to boolean dataview inline fields (like `field:: true` or `field:: false`), so did you mean having a separate configuration option for true and false? Or maybe you mean what I described previously, where you could toggle it for each individual field, so `field_one:: true` would be rendered like now and `field_two:: true #left` would render the checkbox on the left?

**Comment by sfdrada** [comment]
I was thinking a toggle in the settings for each inline type if possible:
Regular inline field = left/right/none
bracketed inline field = left/right/none


However, I can see how this idea can get a little complicated with multiple inline fields on one line, just a thought experiment if you find it valuable.

**Comment by dsarman** [comment]
@sfdrada The feature is implemented in version [0.3.4](https://github.com/dsarman/better-inline-fields/releases/tag/0.3.4).

**Comment by sfdrada** [comment]
You are amazing, thanks for your quick work and dedication to the community!
