### ISSUE TITLE
Not saving values correctly

### ISSUE THREAD

**Issue by sfdrada** [dsarman/better-inline-fields#8]
Tasks do not stay updated after changing the file you are on or minimizing the header. Does not save on any of the checkbox types as far as I am aware. After setting to true and changing files it will default back to false

**Comment by dsarman** [comment]
I forgot to implement this for the new checkbox view options (beginning of line and replace). It should be fixed in version [0.3.5](https://github.com/dsarman/better-inline-fields/releases/tag/0.3.5), please try it out.
