### ISSUE TITLE
Checklist Soundeffect Now Complements Better Inline Fields!

### ISSUE THREAD

**Issue by sfdrada** [dsarman/better-inline-fields#9]
Hey Dsarman,

I've been enjoying your Better Inline Fields plugin and wanted to share something exciting. I've developed a plugin called "Checklist Soundeffect" that plays a sound when checkboxes are checked or unchecked. The cool part? It's already compatible with your plugin!

I think users would love the synergy between our tools. Check it out: [Checklist Soundeffect on GitHub](https://github.com/sfdrada/Checklist-Soundeffect).

Would love to hear your thoughts!

**Comment by dsarman** [comment]
Hi, nice work on the plugin 👍, I have added a link to it to the README.

I am currently not using Obsidian much, as I moved most of my stuff to Logseq (but I still plan to maintain this plugin). Would you mind if I potentially implemented this soundeffect functionality into my Logseq plugin ([logseq-plugin-better-tasks](https://github.com/dsarman/logseq-plugin-better-tasks))?

**Comment by sfdrada** [comment]
No problem at all, open source license my man

**Comment by ooker777** [comment]
@dsarman off-topic: can you share why you move to Logseq?

**Comment by dsarman** [comment]
@ooker777 Mainly the block-based workflow, where it is easy to link and embed any block on page, not just whole pages. Also having query language built in (compared to the Obsidian alternative which is the dataview plugin), and easier to understand plugin API for me.
